version: "2"

services:
  nginx:
    container_name: <%= project.name %>_nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes_from:
      - data
    volumes:
      - ./docker/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./docker/log/nginx:/var/log/nginx
    depends_on:
      - fpm

  fpm:
    container_name: <%= project.name %>_fpm
    image: juliangut/phpdev:<%= project.phpVersion %>-fpm
    environment:
      APP_ENV: development
    volumes_from:
      - data
    volumes:
      - ./docker/log/php:/var/log/php
    depends_on:
      - mysql

  data:
    container_name: <%= project.name %>_data
    image: busybox:latest
    volumes:
      - .:/app

  mysql:
    container_name: <%= project.name %>_mysql
    image: mysql:5.6
    environment:
      MYSQL_USER: <%= project.name %>
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: <%= project.name %>
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
